language: R
cache: packages
sudo: false

warnings_are_errors: false

r:
  - release
  
bioc_required: true
bioc_packages:
  - flowCore
  - flowViz

before_deploy:
  - R -e "install.packages('roxygen2', repos = 'http://cran.rstudio.com')"
  - R -e "staticdocs::build_site(examples = TRUE)"

after_success:
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - lievenclement/flowFDA
  
#r_check_args: "--no-vignettes"
  
script: 
  - |
    travis_wait 30 R CMD build .
    travis_wait 30 R CMD check Phenoflow*tar.gz
